import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const root = process.cwd()
const config = JSON.parse(fs.readFileSync(path.join(root, 'client', 'client.config.json'), 'utf8'))
const outDir = path.join(root, 'dist')
fs.mkdirSync(outDir, { recursive: true })

const payload = {
  assistantName: config.brand.assistantName,
  chatUrl: config.embed.chatUrl.replace(/\/$/, ''),
  greeting: config.embed.greeting,
  logo: new URL(config.brand.logoWhite, `${config.embed.chatUrl.replace(/\/$/, '')}/`).href,
  primary: config.brand.colors.primary,
  secondary: config.brand.colors.secondary,
  position: config.embed.position,
  offsetX: config.embed.offsetX,
  offsetY: config.embed.offsetY,
  panelWidth: config.embed.panelWidth,
  panelHeight: config.embed.panelHeight,
}

const source = `/* Generated by @lantern/chatbot-template. Do not edit directly. */
(function () {
  var c = ${JSON.stringify(payload)};
  var side = c.position === 'left' ? 'left' : 'right';
  var style = document.createElement('style');
  style.textContent = '#chatbot-launcher{position:fixed;bottom:'+c.offsetY+'px;'+side+':'+c.offsetX+'px;z-index:999999;width:60px;height:60px;border:0;border-radius:50%;cursor:pointer;background:linear-gradient(145deg,'+c.secondary+','+c.primary+');box-shadow:0 10px 30px color-mix(in srgb,'+c.primary+' 40%,transparent);display:flex;align-items:center;justify-content:center}#chatbot-launcher img{width:30px;height:30px;object-fit:contain}#chatbot-panel{position:fixed;bottom:'+(c.offsetY+76)+'px;'+side+':'+c.offsetX+'px;z-index:999998;width:'+c.panelWidth+'px;height:'+c.panelHeight+'px;max-width:calc(100vw - 32px);max-height:calc(100vh - 110px);border:1px solid #e2e8f0;border-radius:20px;overflow:hidden;background:#fff;box-shadow:0 24px 60px rgba(15,23,42,.24);display:none}#chatbot-panel.is-open{display:block}#chatbot-panel iframe{width:100%;height:100%;border:0}#chatbot-greeting{position:fixed;bottom:'+(c.offsetY+72)+'px;'+side+':'+c.offsetX+'px;z-index:999997;max-width:240px;padding:12px 36px 12px 14px;border:1px solid #e2e8f0;border-radius:16px;background:#fff;box-shadow:0 12px 30px rgba(15,23,42,.15);font:13px/1.6 sans-serif;color:#334155}#chatbot-greeting button{position:absolute;right:9px;top:8px;border:0;background:none;cursor:pointer;color:#94a3b8}@media(max-width:480px){#chatbot-panel{inset:0;width:100%;height:100%;max-width:none;max-height:none;border-radius:0}}';
  document.head.appendChild(style);
  var panel = document.createElement('div'); panel.id='chatbot-panel'; var frame=document.createElement('iframe'); frame.src=c.chatUrl; frame.title=c.assistantName; frame.loading='lazy'; panel.appendChild(frame); document.body.appendChild(panel);
  var button = document.createElement('button'); button.id='chatbot-launcher'; button.type='button'; button.setAttribute('aria-label','チャットを開く'); var logo=document.createElement('img'); logo.src=c.logo; logo.alt=''; button.appendChild(logo); document.body.appendChild(button);
  if(c.greeting){var greeting=document.createElement('div');greeting.id='chatbot-greeting';greeting.textContent=c.greeting;var close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','案内を閉じる');close.onclick=function(){greeting.remove()};greeting.appendChild(close);document.body.appendChild(greeting)}
  button.onclick=function(){panel.classList.toggle('is-open');if(document.getElementById('chatbot-greeting'))document.getElementById('chatbot-greeting').remove()};
})();
`

const outFile = path.join(outDir, 'chatbot-embed.js')
fs.writeFileSync(outFile, source, 'utf8')
console.log(`Generated: ${path.relative(root, outFile)}`)
